---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: gcredstash
    binary: gcredstash
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gcredstash
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kgaughan/gcredstash/internal.Version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo

homebrew_casks:
  - name: gcredstash
    ids:
      - archives
    homepage: "https://github.com/kgaughan/gcredstash"
    repository:
      owner: kgaughan
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Keith Gaughan
      email: k@stereochro.me
    description: "Manages credentials using AWS Key Management Service (KMS) and DynamoDB"
    license: "ASL 2.0"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gcredstash"]
          end

archives:
  - formats:
      - tar.gz
    id: archives
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

nfpms:
  - id: packages
    file_name_template: >-
      {{ .PackageName }}-{{ .Version }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    description: |-
      Manages credentials using AWS Key Management Service (KMS) and DynamoDB.
    homepage: "https://github.com/kgaughan/gcredstash"
    maintainer: "Keith Gaughan <k+gcredstash@stereochro.me>"
    bindir: /usr/sbin
    license: ASL 2.0
    formats:
      - rpm

kos:
  - build: gcredstash
    base_image: gcr.io/distroless/static:nonroot
    annotations:
      org.opencontainers.image.title: gcredstash
      org.opencontainers.image.description: "Manages credentials using AWS Key Management Service (KMS) and DynamoDB"
      org.opencontainers.image.vendor: "Keith Gaughan"
      org.opencontainers.image.licenses: "ASL 2.0"
      org.opencontainers.image.url: https://github.com/kgaughan/gcredstash
      org.opencontainers.image.source: https://github.com/kgaughan/gcredstash
      org.opencontainers.image.documentation: https://kgaughan.github.io/gcredstash/
      org.opencontainers.image.version: "{{ .Tag }}"
      org.opencontainers.image.revision: "{{ .Commit }}"
      org.opencontainers.image.created: "{{ .Date }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repositories:
      - ghcr.io/kgaughan
    tags:
      - "{{ if not .Prerelease }}latest{{ end }}"
      - "{{.Tag}}"
    creation_time: "{{.CommitTimestamp}}"
    sbom: spdx
    bare: true
    base_import_paths: true
    preserve_import_paths: false
    disable: "{{ .IsSnapshot }}"

checksum:
  algorithm: sha256
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
