---
version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gcredstash
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kgaughan/gcredstash/internal.Version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo

brews:
  - name: gcredstash
    ids:
      - archives
    homepage: "https://github.com/kgaughan/gcredstash"
    repository:
      owner: kgaughan
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Keith Gaughan
      email: k@stereochro.me
    description: "Manages credentials using AWS Key Management Service (KMS) and DynamoDB"
    license: "ASL 2.0"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "gcredstash"

archives:
  - format: tar.gz
    id: archives
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  - id: packages
    file_name_template: >-
      {{ .PackageName }}-{{ .Version }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    description: |-
      Manages credentials using AWS Key Management Service (KMS) and DynamoDB.
    homepage: "https://github.com/kgaughan/gcredstash"
    maintainer: "Keith Gaughan <k+gcredstash@stereochro.me>"
    bindir: /usr/sbin
    license: ASL 2.0
    formats:
      - rpm

dockers:
  - image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE }}:{{ .Tag }}"
    skip_push: auto
    use: buildx
    dockerfile: Dockerfile

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
